Repository Welf06/Beiwe-Chrome-Extension, pull requests merged in 2022-10, with the labels that each got.

#6 onclick events added
  js/popup-backend.js
Labels: hactoberfest-accepted

#7 Revert "onclick events added"
  js/popup-backend.js
Labels: hactoberfest-accepted

#8 Dev
  js/popup-backend.js
Labels: hactoberfest-accepted, hactoberfest

#9 Revert "Dev"
  js/popup-backend.js
Labels: hacktoberfest, hacktoberfest-accepted

#10 Fixed OnClick Events
  js/popup-backend.js
Labels: hacktoberfest, hacktoberfest-accepted

#12 Master Updated
  .gitignore
  assets/Logo.png
  css/style.css
  issues.md
  js/background.js
  js/index.html
  js/popup-backend.js
  js/popup-page.js
  js/script.js
  manifest.json
  popup.html
Labels: hacktoberfest-accepted

#11 popup-page added
  js/popup-page.js
  popup.html
Labels: hacktoberfest-accepted
